#
# To use this configuration:
#   ec validate image ... --policy github.com/enterprise-contract//configs/default.yaml?ref=main
#
description: >
  Use the policy rules from the "minimal" collection. This and other collections are defined in
  https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/release_policy.html#_available_rule_collections
  The minimal collection is a small set of policy rules that should be easy to pass for brand new RHTAP users.
  If a different policy configuration is desired, this resource can serve as a starting point. See the docs on
  how to include and exclude rules at https://redhat-appstudio.github.io/docs.stonesoup.io/ec-policies/policy_configuration.html#_including_and_excluding_rules

publicKey: "k8s://tekton-chains/public-key"

sources:
  - name: Default RHTAP Release Policies
    policy:
      - github.com/enterprise-contract/ec-policies//policy/lib
      - github.com/enterprise-contract/ec-policies//policy/release
    data:
      - github.com/enterprise-contract/ec-policies//data

configuration:
  include:
    - "@minimal"
  exclude:
    # This can be removed once https://issues.redhat.com/browse/OCPBUGS-8428 is addressed
    - step_image_registries
