#
# To use this configuration:
#   ec validate image ... --policy github.com/enterprise-contract//configs/everything.yaml?ref=main
#
description: >
  Identical to the default configuration, but apply every rule instead of just the rules
  in the minimal collection.

publicKey: "k8s://tekton-chains/public-key"

sources:
  - name: Default RHTAP Release Policies
    policy:
      - github.com/enterprise-contract/ec-policies//policy/lib
      - github.com/enterprise-contract/ec-policies//policy/release
    data:
      - github.com/enterprise-contract/ec-policies//data

configuration:
  include:
    - "*"
  exclude:
    # This can be removed once https://issues.redhat.com/browse/OCPBUGS-8428 is addressed
    - step_image_registries
